openapi: 3.0.2
info:
  title: SDNNT API
  description: |-

   Zde bude popis API 

  #  termsOfService: 'https://nkp.cz'
  #  contact:
  #    email: email@email.com
  #  license:
  #    name: Apache 2.0
  #    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0

externalDocs:
  description: Odkaz na stranky sdnnt
  url: 'https://sdnnt.nkp.cz'
servers:
  - url: ../api/v1.0
tags:
  - name: Požadavky
    description: Endpoint, který řeší kompletně správu požadavků
  - name: Katalog
    description: Endpoint pro hledání v katalogu
  - name: SeznamyDNNT
    description: Kompletní seznamy děl zařazených a děl vyřazených ze systému DNNT

paths:

  /catalog:
    get:
      tags:
        - Katalog
      summary: Základní funkcionalita pro nahlížení do katalogu
      description: Poskytuje základní funkcionalitu pro nahlížení do katalogu
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
        - in: query
          name: rows
          schema:
            type: integer
            default: 20
          required: false
        - in: query
          name: page
          schema:
            type: integer
            default: 0
          required: false
        - in: query
          name: sort
          schema:
            type: string
          required: false



      responses:
        '200':
          description: Záznamy z katalogu
          content:
            application/json:
              schema:
                type: object
                properties:
                  requests:
                    type: array
                    items:
                      $ref: '#/components/schemas/CatalogObject'
      security:
        - api_key: []


  /request:
    get:
      tags:
        - Požadavky
      summary: Vrací všechny žádosti pro uživatele
      description: Vrací všechny žádosti, případně filtrované dle stavu
      operationId: requestGet
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: ["open","waiting","processed","rejected","approved"]
          required: false
        - in: query
          name: navrh
          schema:
            type: string
            enum: ["NZN","VVS"]
          required: false
      responses:
        '200':
          description: Všechny uložené žádosti
          content:
            application/json:
              schema:
                type: object
                properties:
                  requests:
                    type: array
                    items:
                      $ref: '#/components/schemas/SavedRequest'
      security:
        - api_key: []


  /request/batch/nzn:
    put:
      tags:
        - Požadavky
      summary: Podání jednoho nebo více návhrhů na zařazení do seznamu DNNT
      description: Řeší hromadné podání navrhů na zařazení do seznamu DNNT
      operationId: requestBatchNzn
      requestBody:
        description: Hromadný návrh (jeden nebo více, identifikátory musí existovat a nesmí se opakovat)
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchRequest'
        required: true

      responses:
        '200':
          description: Žádost vytvořena a ve stavu waiting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponse'
        '400':
          description: Špatný dotaz (syntaxe atd..)
        '404':
          description: Identifikátory nenalezen(y)
        '405':
          description: Chyba validace (datumy atd..)

      security:
        - api_key: []

  /request/batch/vvs:
    put:
      tags:
        - Požadavky
      summary: Požadavek případně více požadavků na vyřazení díla ze seznamu DNNT
      description: Řeší hromadnou hroadný požadavek o vyřazení ze seznamu DNNT
      operationId: requestBatchVvs
      requestBody:
        description: Hromadný požadavek (jeden nebo více, identifikátory musí existovat a nesmí se opakovat)
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchRequest'
        required: true

      responses:
        '200':
          description: Žádost vytvořena a ve stavu waiting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchResponse'
        '400':
          description: Špatný dotaz (syntaxe atd..)
        '404':
          description: Identifikátory nenalezen(y)
        '405':
          description: Chyba validace (datumy atd..)

      security:
        - api_key: []


  /lists/dnnt/enabled:
    get:
      tags:
        - SeznamyDNNT
      summary: Aktuální seznam DNNT
      description: Seznam děl zařazených na seznam sdnnt
      operationId: listDNNTEnabled
      parameters:
        - in: query
          name: date
          schema:
            type: string
            format: date-time
            example: "2017-07-21T17:32:28Z"
          required: false
        - in: query
          name: rows
          schema:
            type: integer
            default: 20
          required: false
        - in: query
          name: page
          schema:
            type: integer
            default: 0
          required: false

      responses:
        '200':
          description: Žádost vytvořena a ve stavu waiting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListsObject'
            application/csv:
              schema:
                type: string
                example: "PID\nuuid:xxxxx"



  /lists/dnnt/disabled:
    get:
      tags:
        - SeznamyDNNT
      summary: Aktuální seznam děl vyřazených ze seznamu DNNT
      description: Seznam děl vyřazených se seznamu DNNT
      operationId: listDNNTDisabled
      parameters:
        - in: query
          name: date
          schema:
            type: string
            format: date-time
            example: "2017-07-21T17:32:28Z"
          required: false
        - in: query
          name: rows
          schema:
            type: integer
            default: 20
          required: false
        - in: query
          name: page
          schema:
            type: integer
            default: 0
          required: false

      responses:
        '200':
          description: Žádost vytvořena a ve stavu waiting
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListsObject'
            application/csv:
              schema:
                type: string
                example: "PID\nuuid:xxxxx"



components:
  schemas:

    # Davkovy pozadavek 
    BatchRequest:
      type: object
      properties:
        batch:
          type: array
          items:
            $ref: '#/components/schemas/Request'
      example:
        batch:
          - datum_zadani: "2021-07-09T07:24:37.210Z"
            identifiers: ['oai:aleph-nkp.cz:SKC01-002839929','oai:aleph-nkp.cz:SKC01-003240356']
            pozadavek: "Pozadavek o zarazeni varky jedna"
            poznamka: "Poznamka A"

          - datum_zadani: "2021-07-09T07:24:37.210Z"
            identifiers: ['oai:aleph-nkp.cz:SKC01-002225134']
            pozadavek: "Pozadavek o zarazeni varky dva"
            poznamka: "Poznamka B"

    # Objekt repreyentujic zaznam v katalogu - vyuzito ve vyhledavani
    CatalogObject:
      type: object
      properties:
        batch:
          type: object
          properties:
            id:
              type: string
            message:
              type: string
      example:
        batch:
          id: "admin-0123445"
          message: "Cannot find batch 'admin-0123445'"

    # Objekt repreyentujic zaznam v katalogu - vyuzito ve vyhledavani
    ListsObject:
      type: array
      items:
        type: object
        properties:
          pid:
            type: string
      example:
        - pid: "uuid:xxxx"
        - pid: "uuid:yyyy"


    # Batch
    ErrorObject:
      type: object
      properties:
        batch:
          type: object
          properties:
            id:
              type: string
            message:
              type: string
      example:
        batch:
          id: "admin-0123445"
          message: "Cannot find batch 'admin-0123445'"



    # Zadost / Navrh na zarazeni a pozadavek na vyrazeni 
    Request:
      type: object
      properties:
        identifiers:
          type: array
          items:
            type: string
        datum_zadani:
          type: string
          format: date-time
        pozadavek:
          type: string
        poznamka:
          type: string
      example:
        identifiers: ['oai:aleph-nkp.cz:SKC01-002839929','oai:aleph-nkp.cz:SKC01-003240356']
        datum_zadani: '2021-07-09T07:12:55.366Z'
        pozadavek: 'Pozadavek o zarazeni do seznamu DNNT'
        poznamka: 'Poznamka'


    # Neulozena zadost
    NotSavedRequest:
      allOf:
        - $ref: '#/components/schemas/Request'
        - type: object
          properties:
            id:
              type: string
            navrh:
              type: string
            user:
              type: string
            state:
              type: string
            reason:
              type: string
      example:
        user: 'admin'
        identifiers: ['oai:aleph-nkp.cz:SKC01-002839929']
        datum_zadani: '2021-07-09T07:12:55.366Z'
        pozadavek: 'Pozadavek o zarazeni do seznamu DNNT'
        poznamka: 'Poznamka'
        reason: 'Cannot find identifier oai:aleph-nkp.cz:SKC01-002839929'

    # Ulozena zadost
    SavedRequest:
      allOf:
        - $ref: '#/components/schemas/Request'
        - type: object
          properties:
            id:
              type: string
            navrh:
              type: string
            indextime:
              type: string
              format: date-time
            user:
              type: string
            state:
              type: string
      example:
        user: 'admin'
        identifiers: ['oai:aleph-nkp.cz:SKC01-002839929','oai:aleph-nkp.cz:SKC01-003240356']
        datum_zadani: '2021-07-09T07:12:55.366Z'
        pozadavek: 'Pozadavek o zarazeni do seznamu DNNT'
        poznamka: 'Poznamka'
        indextime: '2021-07-09T07:12:55.366Z'

    # Odpoved z endpoitu pro davkove zpracovani
    BatchResponse:
      type: object
      properties:
        saved:
          type: array
          items:
            $ref: '#/components/schemas/SavedRequest'
        notsaved:
          type: array
          items:
            $ref: '#/components/schemas/NotSavedRequest'



  securitySchemes:

    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
